# Configuration Split setting menu items definition
entity.config_feature.collection:
  title: 'Configuration Features settings'
  description: 'List Configuration Feature settings.'
  route_name: entity.config_feature.collection
  parent: system.admin_config_development
